language: c
matrix:
    include:
        - compiler: gcc
        - compiler: clang
          env: CFLAGS="-g -O2"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install debhelper autotools-dev dh-autoreconf file pkg-config build-essential
script: (cd src && make hello)
